name: Frontend Build & Test

on:
  push:
    paths:
      - 'frontend-ucens/**'
  pull_request:
    paths:
      - 'frontend-ucens/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node 20
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install deps
      run: npm install --legacy-peer-deps
      working-directory: frontend-ucens 

    - name: Run Unit Tests
      run: npm test -- --watch=false --browsers=ChromeHeadless
      working-directory: frontend-ucens

    - name: Build Angular
      run: npm run build
      working-directory: frontend-ucens